# Generated by Django 4.0.3 on 2022-07-03 22:28

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('contacto', models.CharField(max_length=20)),
                ('valido', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Utilizador',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('utilizador_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utilizadores.utilizador')),
            ],
            options={
                'db_table': 'Administrador',
            },
            bases=('utilizadores.utilizador',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('utilizador_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utilizadores.utilizador')),
                ('nif', models.IntegerField(blank=True, db_column='NIF', null=True)),
                ('morada', models.CharField(blank=True, db_column='Morada', max_length=255, null=True)),
                ('data_de_nascimento', models.DateTimeField(blank=True, db_column='Data de nascimento', null=True)),
            ],
            options={
                'db_table': 'Cliente',
            },
            bases=('utilizadores.utilizador',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('utilizador_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utilizadores.utilizador')),
                ('funcao', models.CharField(blank=True, db_column='Funcao', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Funcionario',
            },
            bases=('utilizadores.utilizador',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
